version: '3.4'

services:
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
        ports:
            - 5432:5434
        volumes:
            - postgres:/var/lib/postgresql/data

volumes:
    postgres:
